# This workflow will build and package the AzanUI React app as a Node.js server executable
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Package AzanUI React App as Node.js Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install --legacy-peer-deps

      - name: build React app
        run: npm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Build server executable
        run: |
          npx pkg server.js --targets node18-win-x64,node18-linux-x64,node18-macos-x64 --out-path dist

      - name: Rename executables
        run: |
          mv dist/server-win.exe AzanUI-server-win.exe || true
          mv dist/server-linux AzanUI-server-linux || true
          mv dist/server-macos AzanUI-server-macos || true

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: AzanUI-server-executables
          path: |
            AzanUI-server-win.exe
            AzanUI-server-linux
            AzanUI-server-macos
